{% set name = "gnupg" %}
{% set version = "2.3.3" %}
{% set sha256 = "5789b86da6a1a6752efb38598f16a77af51170a8494039c3842b085032e8e937" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - export CPPFLAGS="-DIN_EXCL_UNLINK=0x04000000 $CPPFLAGS"  # [linux]
    - export LDFLAGS="-lrt $LDFLAGS"                           # [linux]
    - ./configure --prefix="$PREFIX"
    - make
    - make install
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('gnupg', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bzip2
    - sqlite
    - libgcrypt
    - libgpg-error
    - libksba
    - libassuan
    - ntbtls
    - npth
    - readline
    - libiconv
  run:
    - bzip2
    - readline
    - libiconv
    - sqlite

test:
  commands:
    - gpg --help

about:
  home: https://www.gnupg.org
  summary: The New GNU Privacy Guard
  license: LGPL-3
  license_family: GPL
  license_file: COPYING
  description: |
    GnuPG is a complete and free implementation of the OpenPGP standard as defined
    by RFC4880 (also known as PGP). GnuPG allows you to encrypt and sign your data
    and communications; it features a versatile key management system, along with
    access modules for all kinds of public key directories. GnuPG, also known as GPG,
    is a command line tool with features for easy integration with other applications.
    A wealth of frontend applications and libraries are available. GnuPG also provides
    support for S/MIME and Secure Shell (ssh).

extra:
  recipe-maintainers:
    - zklaus
    - mariusvniekerk
