{% set name = "gnupg" %}
{% set version = "1.4.23" %}

package:
  # Additional suffix of 1 to make it co-installable with gnupg>=2
  name: {{ name|lower }}1
  version: {{ version }}

source:
  url: https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-{{ version }}.tar.bz2
  sha256: c9462f17e651b6507848c08c430c791287cd75491f8b5a8b50c6ed46b12678ba
  patches:
    # GnuPG-bug-id: 5215
    - patches/Avoid-use-of-COMMON-section-for-all-cases.patch
    - patches/Add-m4-extern-inline-m4-from-gnulib.patch
    - patches/Fix-for-RISC-OS-which-doesnt-allow-COMMON-section.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('gnupg1', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - libgpg-error  # [build_platform != target_platform]
  host:
    - bzip2
    - sqlite
    - libgcrypt
    - libksba
    - libassuan
    - libcurl
    - ntbtls
    - npth
    - readline
    - libiconv
  run:
    - bzip2
    - readline
    - libiconv
    - sqlite

test:
  commands:
    - gpg1 --help

about:
  home: https://www.gnupg.org
  summary: The New GNU Privacy Guard
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  description: |
    GnuPG is a complete and free implementation of the OpenPGP standard as defined
    by RFC4880 (also known as PGP). GnuPG allows you to encrypt and sign your data
    and communications; it features a versatile key management system, along with
    access modules for all kinds of public key directories. GnuPG, also known as GPG,
    is a command line tool with features for easy integration with other applications.
    A wealth of frontend applications and libraries are available. GnuPG also provides
    support for S/MIME and Secure Shell (ssh).

extra:
  recipe-maintainers:
    - zklaus
    - mariusvniekerk
    - xhochy
