{% set name = "gnupg" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-{{ version }}.tar.bz2
  sha256: 7f404ccc6a58493fedc15faef59f3ae914831cff866a23f0bf9d66cfdd0fea29

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('gnupg', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - libgpg-error  # [build_platform != target_platform]
  host:
    - bzip2
    - sqlite
    - libgcrypt
    - libgpg-error
    - libksba
    - libassuan
    - ntbtls
    - npth
    - readline
    - libiconv
  run:
    - bzip2
    - readline
    - libiconv
    - sqlite

test:
  commands:
    - gpg --help

about:
  home: https://www.gnupg.org
  summary: The New GNU Privacy Guard
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  description: |
    GnuPG is a complete and free implementation of the OpenPGP standard as defined
    by RFC4880 (also known as PGP). GnuPG allows you to encrypt and sign your data
    and communications; it features a versatile key management system, along with
    access modules for all kinds of public key directories. GnuPG, also known as GPG,
    is a command line tool with features for easy integration with other applications.
    A wealth of frontend applications and libraries are available. GnuPG also provides
    support for S/MIME and Secure Shell (ssh).

extra:
  recipe-maintainers:
    - zklaus
    - mariusvniekerk
    - xhochy
