# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fpNF11xqkTSUk3VDd4qwknNjsNDrbkc46usocsgWDml/LyoBRgMZMSVg8+U0moM3QxRadX+g2ahtce9xhkrdhmhgiS0NOJghtTNKhCfBU0pU+SLBNnp9roxp4LytNDD4QNoWtS2pka+FhnQZ99mBcUSwTq/hcgHtyIhEu+kYb3TXXxzsLAzngEbhDslrf9alx52nXchDEwNjEw8VYQy/aeu9VCrhWVbU6VYrAF9XPZMAJhX9uw/6P/tufFqV+XKojIdv9BO7Q18OsWGh0KSdZHPfCn6Xzy99QVUdHUxKceHYjbLSsOasEv5zfVTmG31w/wSt0gWWKQi6sh8ApIJEwFBh5pJsb316UkONvR6colbFXfwxS2dUkIcU0/b20cPwBXQa+0rl1s2ruJ2Xhig9mHKG/GIf2XkDs6rDfIbAgWqQn2KibKypXrDkxjy1fVnY+OIjJWOAUcw4yy8tcZHZcDhaYJbKZsJgjoh6Xig/LnxvXkJLv+VUmjPu8RdKq9xE9FrqVwNqjzTFK0Eim/S2Z07MIHCz9CFwMqnFS4TR7WYvt6Bu2lgK5iO1DhqLostnLqgHGrJYccMItQugRLLBuarzdQqHOOPmdv+89fbv7+XbqOoPga746FJfCbTykZUJxFcSCf9wgKPos1Ya6m64ydNdHcLO0nAx8AlKhXSXO/U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
