appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fpNF11xqkTSUk3VDd4qwknNjsNDrbkc46usocsgWDml/LyoBRgMZMSVg8+U0moM3QxRadX+g2ahtce9xhkrdhmhgiS0NOJghtTNKhCfBU0pU+SLBNnp9roxp4LytNDD4QNoWtS2pka+FhnQZ99mBcUSwTq/hcgHtyIhEu+kYb3TXXxzsLAzngEbhDslrf9alx52nXchDEwNjEw8VYQy/aeu9VCrhWVbU6VYrAF9XPZMAJhX9uw/6P/tufFqV+XKojIdv9BO7Q18OsWGh0KSdZHPfCn6Xzy99QVUdHUxKceHYjbLSsOasEv5zfVTmG31w/wSt0gWWKQi6sh8ApIJEwFBh5pJsb316UkONvR6colbFXfwxS2dUkIcU0/b20cPwBXQa+0rl1s2ruJ2Xhig9mHKG/GIf2XkDs6rDfIbAgWqQn2KibKypXrDkxjy1fVnY+OIjJWOAUcw4yy8tcZHZcDhaYJbKZsJgjoh6Xig/LnxvXkJLv+VUmjPu8RdKq9xE9FrqVwNqjzTFK0Eim/S2Z07MIHCz9CFwMqnFS4TR7WYvt6Bu2lgK5iO1DhqLostnLqgHGrJYccMItQugRLLBuarzdQqHOOPmdv+89fbv7+XbqOoPga746FJfCbTykZUJxFcSCf9wgKPos1Ya6m64ydNdHcLO0nAx8AlKhXSXO/U=}
